# Generated by Django 4.1.6 on 2023-03-01 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0007_alter_goalcategory_board'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='board',
            options={'verbose_name': 'Общая доска целей', 'verbose_name_plural': 'Общие доски целей'},
        ),
    ]
