name: todolist ci/cd
on: [push]
jobs:
  build_and_push_project:
      runs-on: ubuntu-latest
      steps:
        - name: clone code
          uses: actions/checkout@v3
        - name: docker build
          run: docker build -t azaiko/django-api:$GITHUB_REF_NAME-$GITHUB_RUN_ID .
        - name: docker login
          run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        - name: docker push
          run: docker push azaiko/django-api:$GITHUB_REF_NAME-$GITHUB_RUN_ID
  deploy_project:
    runs-on: ubuntu-latest
    needs: build_and_push_project
    env:
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
    steps:
      - name: clone code
        uses: actions/checkout@v3
      - name: render
        run: |
          mkdir deploy
          cat docker-compose-server.yml | envsubst > deploy/docker-compose.yml
      - name: transfer code to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_NAME }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          source: "deploy/docker-compose.yml"
          target: "django-api"
          strip_components: 1
      - name: deploy app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_NAME }}
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            cd django-api
            echo ${{ secrets.SERVER_PASSWORD}} | sudo -S docker-compose up -d

