name: todolist ci/cd
on: [push]
jobs:

  build_and_push_project:  # Создаём образ проекта и сохраняем в DockerHub
      runs-on: ubuntu-latest
      steps:
        - name: clone code
          uses: actions/checkout@v3
        - name: docker build
          run: docker build -t azaiko/django-api:$GITHUB_REF_NAME-$GITHUB_RUN_ID .
        - name: docker login
          run: echo ${{ secrets.DOCKERHUB_TOKEN }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
        - name: docker push
          run: docker push azaiko/django-api:$GITHUB_REF_NAME-$GITHUB_RUN_ID

  deploy_project:  # Разворачиваем образ проекта на сервере
    runs-on: ubuntu-latest
    needs: build_and_push_project
    env:
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_NAME: ${{ secrets.DB_NAME }}
      SECRET_KEY: ${{ secrets.SECRET_KEY }}
      DB_ENGINE: ${{ secrets.DB_ENGINE }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      VK_ID: ${{ secrets.VK_ID }}
      VK_KEY: ${{ secrets.VK_KEY }}
      BOT_TOKEN: {{ secrets.BOT_TOKEN }}
    steps:
      - name: clone code
        uses: actions/checkout@v3
      - name: render
        run: |
          mkdir deploy
          cat docker-compose-server.yml | envsubst > deploy/docker-compose.yml
          cat docker.env | envsubst > deploy/docker.env
          cat nginx.conf > deploy/nginx.conf
      - name: transfer code to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          source: "deploy/docker-compose.yml,deploy/docker.env,deploy/nginx.conf"
          target: "django-api"
          strip_components: 1
      - name: deploy app
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd django-api
            echo ${{ secrets.PASSWORD}} | sudo -S docker compose up -d
